### PR TITLE
lots of duplicate removed and created test for the helper method created

### PR DESCRIPTION
**Pull request by girishramnani**
created a helper validate() for type checking and null checking , then replaced the validate method of all the actions and services with the helper. Ran the test and the got all successfully correct.
there were no guidelines how to contribute so pull request sent to master.

### CODE REVIEW

**Comment by sacheendra** [comment]
Hi Girish,
Thank you for contributing. 

The tests use the code in the _dist_ folder. The code from the _src_ folder is transpiled by babel and stored in _dist_. The library uses grunt to automate this. Running `grunt watch` in the folder will do this. 

A small styling change is also required, the library does not use semi-colons at statement endings. 

I would also recommend squashing the commits into a single commit. http://push.cwcon.org/learn/squashing-commits.html

I'll put up some instructions as soon as possible.

**Comment by girishramnani** [comment]
squashed the helpers , also the semi-colons that could be done by fixmyjs, also create a default task of build on gruntfile. could be helpful. And just a suggestion even when i removed the validation method while i was coding , the test passed so maybe the tests could be more like edge-casy.also could use istambul for code coverage with something like the codecov?. Would you like me to open an issue?

**Comment by sacheendra** [comment]
Feel free to open an issue. 

Also add the _dist_ folder to the commit. That is the code that is used by the users of the library and on which the tests are run. 

Will work on adding more tests ASAP.

**Comment by girishramnani** [comment]
ok

**Comment by girishramnani** [comment]
generated the dist and can i help on the testing and coverage part?

**Comment by girishramnani** [comment]
also should i create a new pull request?

**Comment by girishramnani** [comment]
Ok so all the old commits on the pull request were also squashed. great then no new pull request is required i guess.

**Comment by sacheendra** [comment]
Hey girish,

Have a look at helpers.js and see how the code is styled. I am working on adding automatic linting.

**Comment by girishramnani** [comment]
U can use fixmyjs and also why are all the ; missing ?  :laughing:

**Comment by sacheendra** [comment]
Semicolons are not required in JS and just redundant. We follow a style without semicolons. 

Still figuring out how to use fixmyjs.

**Pull request merged**
